name: c2logbook
description: A Dart wrapper providing an Object-Oriented interface to the Concept2 Logbook API 
version: 0.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.0.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  oauth2: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  analysis_options: any
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
